[1: var3] Best node: 57.5:1 (1.739%) [ 117(train) | 121(test) ] for params (-25.3451590165576, 0.0454266871440112). | was stored!
[2: var15] Best node: Inf:1 (0%) [ 29(train) | 30(test) ] for params (-2.17670728041299, 5.54871563487297). | was stored!
[3: imp_ent_var16_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[4: imp_op_var39_comer_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[5: imp_op_var39_comer_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[6: imp_op_var40_comer_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[7: imp_op_var40_comer_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[8: imp_op_var40_efect_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[9: imp_op_var40_efect_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[10: imp_op_var40_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[11: imp_op_var41_comer_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[12: imp_op_var41_comer_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[13: imp_op_var41_efect_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[14: imp_op_var41_efect_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[15: imp_op_var41_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[16: imp_op_var39_efect_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[17: imp_op_var39_efect_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[18: imp_op_var39_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[19: imp_sal_var16_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[20: ind_var1_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[21: ind_var1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[22: ind_var5_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[23: ind_var5] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[24: ind_var6_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[25: ind_var6] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[26: ind_var8_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[27: ind_var8] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[28: ind_var12_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[29: ind_var12] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[30: ind_var13_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[31: ind_var13_corto_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[32: ind_var13_corto] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[33: ind_var13_largo_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[34: ind_var13_largo] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[35: ind_var13_medio_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[36: ind_var13] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[37: ind_var14_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[38: ind_var14] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[39: ind_var17_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[40: ind_var17] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[41: ind_var18_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[42: ind_var19] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[43: ind_var20_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[44: ind_var20] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[45: ind_var24_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[46: ind_var24] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[47: ind_var25_cte] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[48: ind_var26_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[49: ind_var26_cte] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[50: ind_var25_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[51: ind_var30_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[52: ind_var30] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[53: ind_var31_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[54: ind_var31] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[55: ind_var32_cte] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[56: ind_var32_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[57: ind_var33_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[58: ind_var33] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[59: ind_var34_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[60: ind_var37_cte] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[61: ind_var37_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[62: ind_var39_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[63: ind_var40_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[64: ind_var40] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[65: ind_var41_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[66: ind_var44_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[67: ind_var44] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[68: num_var1_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[69: num_var1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[70: num_var4] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[71: num_var5_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[72: num_var5] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[73: num_var6_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[74: num_var6] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[75: num_var8_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[76: num_var8] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[77: num_var12_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[78: num_var12] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[79: num_var13_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[80: num_var13_corto_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[81: num_var13_corto] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[82: num_var13_largo_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[83: num_var13_largo] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[84: num_var13_medio_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[85: num_var13] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[86: num_var14_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[87: num_var14] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[88: num_var17_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[89: num_var17] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[90: num_var18_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[91: num_var20_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[92: num_var20] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[93: num_var24_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[94: num_var24] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[95: num_var26_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[96: num_var25_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[97: num_op_var40_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[98: num_op_var40_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[99: num_op_var40_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[100: num_op_var40_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[101: num_op_var41_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[102: num_op_var41_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[103: num_op_var41_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[104: num_op_var41_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[105: num_op_var39_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[106: num_op_var39_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[107: num_op_var39_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[108: num_op_var39_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[109: num_var30_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[110: num_var30] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[111: num_var31_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[112: num_var31] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[113: num_var32_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[114: num_var33_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[115: num_var33] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[116: num_var34_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[117: num_var35] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[118: num_var37_med_ult2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[119: num_var37_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[120: num_var39_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[121: num_var40_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[122: num_var40] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[123: num_var41_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[124: num_var42_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[125: num_var42] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[126: num_var44_0] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[127: num_var44] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[128: saldo_var1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[129: saldo_var5] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[130: saldo_var6] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[131: saldo_var8] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[132: saldo_var12] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[133: saldo_var13_corto] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[134: saldo_var13_largo] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[135: saldo_var13_medio] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[136: saldo_var13] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[137: saldo_var14] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[138: saldo_var17] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[139: saldo_var18] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[140: saldo_var20] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[141: saldo_var24] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[142: saldo_var26] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[143: saldo_var25] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[144: saldo_var30] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[145: saldo_var31] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[146: saldo_var32] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[147: saldo_var33] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[148: saldo_var34] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[149: saldo_var37] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[150: saldo_var40] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[151: saldo_var42] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[152: saldo_var44] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[153: var36] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[154: delta_imp_amort_var18_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[155: delta_imp_amort_var34_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[156: delta_imp_aport_var13_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[157: delta_imp_aport_var17_1y3] Best node: 55:1 (1.818%) [ 56(train) | 56(test) ] for params (-0.022378137197284, 44.6861865652448). | was stored!
[158: delta_imp_aport_var33_1y3] Best node: Inf:1 (0%) [ 18(train) | 23(test) ] for params (-0.00851179207925097, 117.483461146451). | was stored!
[159: delta_imp_compra_var44_1y3] Best node: 43:1 (2.326%) [ 88(train) | 92(test) ] for params (-0.0312356822644184, 32.0144605180478). | was stored!
[160: delta_imp_reemb_var13_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[161: delta_imp_reemb_var17_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[162: delta_imp_reemb_var33_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[163: delta_imp_trasp_var17_in_1y3] Best node: Inf:1 (0%) [ 6(train) | 14(test) ] for params (-0.00889030513642251, 112.481479986348). | was stored!
[164: delta_imp_trasp_var17_out_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[165: delta_imp_trasp_var33_in_1y3] Best node: Inf:1 (0%) [ 11(train) | 19(test) ] for params (-0.0105817499447253, 94.5017896226314). | was stored!
[166: delta_imp_trasp_var33_out_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[167: delta_imp_venta_var44_1y3] Best node: Inf:1 (0%) [ 43(train) | 33(test) ] for params (-0.0219318000164788, 45.5956018788606). | was stored!
[168: delta_num_aport_var13_1y3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[169: delta_num_aport_var17_1y3] Best node: 55:1 (1.818%) [ 56(train) | 56(test) ] for params (-0.0223781371971755, 44.6861865652447). | was stored!
[170: delta_num_aport_var33_1y3] Best node: Inf:1 (0%) [ 18(train) | 23(test) ] for params (-0.00851179207990416, 117.483461146451). | was stored!
[171: delta_num_compra_var44_1y3] Best node: 43:1 (2.326%) [ 88(train) | 92(test) ] for params (-0.0312356822646584, 32.0144605180478). | was stored!
[172: delta_num_venta_var44_1y3] Best node: Inf:1 (0%) [ 43(train) | 33(test) ] for params (-0.0219318000165745, 45.5956018788606). | was stored!
[173: imp_amort_var18_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[174: imp_amort_var34_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[175: imp_aport_var13_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[176: imp_aport_var13_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[177: imp_aport_var17_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[178: imp_aport_var17_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[179: imp_aport_var33_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[180: imp_aport_var33_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[181: imp_var7_emit_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[182: imp_var7_recib_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[183: imp_compra_var44_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[184: imp_compra_var44_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[185: imp_reemb_var13_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[186: imp_reemb_var17_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[187: imp_reemb_var17_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[188: imp_reemb_var33_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[189: imp_var43_emit_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[190: imp_trans_var37_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[191: imp_trasp_var17_in_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[192: imp_trasp_var17_in_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[193: imp_trasp_var17_out_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[194: imp_trasp_var33_in_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[195: imp_trasp_var33_in_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[196: imp_trasp_var33_out_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[197: imp_venta_var44_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[198: imp_venta_var44_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[199: ind_var7_emit_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[200: ind_var7_recib_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[201: ind_var10_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[202: ind_var10cte_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[203: ind_var9_cte_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[204: ind_var9_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[205: ind_var43_emit_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[206: ind_var43_recib_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[207: var21] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[208: num_aport_var13_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[209: num_aport_var13_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[210: num_aport_var17_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[211: num_aport_var17_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[212: num_aport_var33_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[213: num_aport_var33_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[214: num_var7_emit_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[215: num_var7_recib_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[216: num_compra_var44_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[217: num_compra_var44_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[218: num_ent_var16_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[219: num_var22_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[220: num_var22_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[221: num_var22_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[222: num_var22_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[223: num_med_var22_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[224: num_med_var45_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[225: num_meses_var5_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[226: num_meses_var8_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[227: num_meses_var12_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[228: num_meses_var13_corto_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[229: num_meses_var13_largo_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[230: num_meses_var13_medio_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[231: num_meses_var17_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[232: num_meses_var29_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[233: num_meses_var33_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[234: num_meses_var39_vig_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[235: num_meses_var44_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[236: num_op_var39_comer_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[237: num_op_var39_comer_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[238: num_op_var40_comer_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[239: num_op_var40_comer_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[240: num_op_var40_efect_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[241: num_op_var40_efect_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[242: num_op_var41_comer_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[243: num_op_var41_comer_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[244: num_op_var41_efect_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[245: num_op_var41_efect_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[246: num_op_var39_efect_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[247: num_op_var39_efect_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[248: num_reemb_var13_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[249: num_reemb_var17_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[250: num_reemb_var17_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[251: num_reemb_var33_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[252: num_sal_var16_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[253: num_var43_emit_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[254: num_var43_recib_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[255: num_trasp_var11_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[256: num_trasp_var17_in_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[257: num_trasp_var17_in_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[258: num_trasp_var17_out_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[259: num_trasp_var33_in_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[260: num_trasp_var33_in_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[261: num_trasp_var33_out_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[262: num_venta_var44_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[263: num_venta_var44_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[264: num_var45_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[265: num_var45_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[266: num_var45_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[267: num_var45_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[268: saldo_medio_var5_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[269: saldo_medio_var5_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[270: saldo_medio_var5_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[271: saldo_medio_var5_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[272: saldo_medio_var8_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[273: saldo_medio_var8_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[274: saldo_medio_var8_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[275: saldo_medio_var8_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[276: saldo_medio_var12_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[277: saldo_medio_var12_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[278: saldo_medio_var12_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[279: saldo_medio_var12_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[280: saldo_medio_var13_corto_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[281: saldo_medio_var13_corto_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[282: saldo_medio_var13_corto_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[283: saldo_medio_var13_corto_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[284: saldo_medio_var13_largo_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[285: saldo_medio_var13_largo_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[286: saldo_medio_var13_largo_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[287: saldo_medio_var13_largo_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[288: saldo_medio_var13_medio_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[289: saldo_medio_var13_medio_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[290: saldo_medio_var17_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[291: saldo_medio_var17_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[292: saldo_medio_var17_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[293: saldo_medio_var17_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[294: saldo_medio_var29_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[295: saldo_medio_var29_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[296: saldo_medio_var29_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[297: saldo_medio_var29_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[298: saldo_medio_var33_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[299: saldo_medio_var33_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[300: saldo_medio_var33_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[301: saldo_medio_var33_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[302: saldo_medio_var44_hace2] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[303: saldo_medio_var44_hace3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[304: saldo_medio_var44_ult1] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[305: saldo_medio_var44_ult3] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[306: var38] Failed to optimize with gradient descent (you should loose conditions!). | was useless!
[307: n0] Best node: Inf:1 (0%) [ 20(train) | 15(test) ] for params (-6.45790415682984, 1.43212273627226). | was stored!


-----
Summary:
Train rows soft-ruled: 344 (pure: 125)
Test rows soft-ruled: 341 (pure: 125)
