setwd("C:/Users/Laurae/Documents/Data Science/Santander/") ##set your own working directory
source("Santander Feature Engineering Set.R")

train <- read.csv("train.csv")
test  <- read.csv("test.csv")
full_data <- rbind(train[, -371], test)

full_data <- cbind(full_data, CreateFeatures(data, "var1"))
full_data <- cbind(full_data, CreateFeatures(data, "var2"))
full_data <- cbind(full_data, CreateFeatures(data, "var5"))
full_data <- cbind(full_data, CreateFeatures(data, "var7"))
full_data <- cbind(full_data, CreateFeatures(data, "var8"))
full_data <- cbind(full_data, CreateFeatures(data, "var9"))
full_data <- cbind(full_data, CreateFeatures(data, "var10"))
full_data <- cbind(full_data, CreateFeatures(data, "var12"))
full_data <- cbind(full_data, CreateFeatures(data, "var13"))
full_data <- cbind(full_data, CreateFeatures(data, "var14"))
full_data <- cbind(full_data, CreateFeatures(data, "var16"))
full_data <- cbind(full_data, CreateFeatures(data, "var17"))
full_data <- cbind(full_data, CreateFeatures(data, "var18"))
full_data <- cbind(full_data, CreateFeatures(data, "var20"))
full_data <- cbind(full_data, CreateFeatures(data, "var22"))
full_data <- cbind(full_data, CreateFeatures(data, "var24"))
full_data <- cbind(full_data, CreateFeatures(data, "var25"))
full_data <- cbind(full_data, CreateFeatures(data, "var26"))
full_data <- cbind(full_data, CreateFeatures(data, "var27"))
full_data <- cbind(full_data, CreateFeatures(data, "var28"))
full_data <- cbind(full_data, CreateFeatures(data, "var29"))
full_data <- cbind(full_data, CreateFeatures(data, "var30"))
full_data <- cbind(full_data, CreateFeatures(data, "var31"))
full_data <- cbind(full_data, CreateFeatures(data, "var32"))
full_data <- cbind(full_data, CreateFeatures(data, "var33"))
full_data <- cbind(full_data, CreateFeatures(data, "var34"))
full_data <- cbind(full_data, CreateFeatures(data, "var37"))
full_data <- cbind(full_data, CreateFeatures(data, "var39"))
full_data <- cbind(full_data, CreateFeatures(data, "var40"))
full_data <- cbind(full_data, CreateFeatures(data, "var41"))
full_data <- cbind(full_data, CreateFeatures(data, "var43"))
full_data <- cbind(full_data, CreateFeatures(data, "var44"))
full_data <- cbind(full_data, CreateFeatures(data, "var45"))
full_data <- cbind(full_data, CreateFeatures(data, "var46"))

train_temp <- full_data[1:76020, ]
test_temp <- full_data[76021:151838, ]
